# Generated by Django 2.2.10 on 2020-08-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Bought',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Instock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Sold',
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bought', models.IntegerField()),
                ('Sold', models.IntegerField()),
                ('Instock', models.BooleanField()),
                ('Quantity', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Item')),
            ],
        ),
    ]
