# Generated by Django 2.2.10 on 2020-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200827_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
