# Generated by Django 2.2.10 on 2020-08-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Category',
        ),
        migrations.AddField(
            model_name='brand',
            name='Category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Category'),
        ),
    ]
