# Generated by Django 2.2.10 on 2020-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='Location',
            field=models.TextField(),
        ),
    ]
