# Generated by Django 2.2.10 on 2020-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Cut',
            field=models.IntegerField(null=True),
        ),
    ]
