# Generated by Django 2.2.10 on 2020-08-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_brand_cut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Cart'),
        ),
    ]
