# Generated by Django 2.2.10 on 2020-08-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200828_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Userdetail'),
        ),
    ]
