# Generated by Django 2.2.10 on 2020-08-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200829_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Session',
            new_name='Cart',
        ),
    ]
