# Generated by Django 2.2.10 on 2020-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200829_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Bill',
            field=models.IntegerField(null=True),
        ),
    ]
