# Generated by Django 2.2.10 on 2020-08-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
