# Generated by Django 2.2.10 on 2020-08-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20200830_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Bought',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Sold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Bill',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=60)),
                ('Location', models.TextField()),
                ('Wakati', models.DateTimeField(null=True)),
                ('Cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Cart')),
            ],
        ),
    ]
