# Generated by Django 2.2.10 on 2020-08-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20200830_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='Wakati',
            new_name='Ordertime',
        ),
        migrations.AddField(
            model_name='delivery',
            name='Deltime',
            field=models.TimeField(null=True),
        ),
    ]
