# Generated by Django 2.2.10 on 2021-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210329_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='Fee',
            field=models.IntegerField(default=50),
        ),
    ]
